### ISSUE TITLE
Icon Button Brand: Beim Umstellen auf Desktop-Functional switcht die Iconfarbe auf schwarz

### ISSUE THREAD

**Issue by hannastephaniahahn** [db-ui/design-feedback#111]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

0.3.2

### Reproduction case

Figma im Browser: Auf Komponente "Icon Button -> Brand" klicken und Adaptive Size auf "Desktop-Functional" stellen.

### Expected

Icon Farbe bleibt gleich

### Screenshots

![image](https://github.com/user-attachments/assets/3f45a103-8720-4546-8d9c-336ea5aee1ef)

**Comment by leape** [comment]
Wird als Ticket in den Jira Backlog aufgenommen und in einem der nächsten Sprints bearbeitet.

**Comment by leape** [comment]
Scheint ein bekannter Bug von Figma zu sein (siehe [Community-Post](https://forum.figma.com/t/instance-swapped-icons-do-not-receive-color-updates-anymore/54334/))
Habe eine Support-Anfrage an das Figma-Team geschickt und das Problem inkl. [Beispiel](https://www.figma.com/design/Jqgx3nu9btd9vGf5FxmQ0x/Color-mapping-reset-when-variable-mode-is-changed?node-id=0-1&t=KNS27urytY6eZZvQ-1) geschildert.
Ggf. müssen wir dann einen Workaround bei allen betroffenen Komponenten einbauen (Farbfläche + Icon als Maske, siehe Beispiel).

In der Zwischenzeit müssen die Icons leider manuell korrekt eingefärbt werden, wenn mit den Densities Functional und Expressive gearbeitet wird.
