### ISSUE TITLE
Check Box - Desktop-Functional - Checked Haken nicht erkennbar, da schwarz statt weiß

### ISSUE THREAD

**Issue by estherux** [db-ui/design-feedback#119]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Reproduction case

Bei einfügen der Instanz - Check Box - Desktop Function checked, ist kein weißer Haken ersichtlich, die Box ist komplett schwarz ausgefüllt

### Expected

Farbe nicht befüllt > siehe Auswahl,  bei Desktop - Regular ist es vorhanden

### Screenshots

![image](https://github.com/user-attachments/assets/4a505528-652a-4eac-a54e-e31fa39b892b)

**Comment by leape** [comment]
Bug der Icons in Densities Functional und Expressive
Duplikat zu https://github.com/db-ui/design-feedback/issues/111

**Comment by leape** [comment]
@estherux siehe https://github.com/db-ui/design-feedback/issues/111#issuecomment-2410898997
