### ISSUE TITLE
Grid fürs neue Design System

### ISSUE THREAD

**Issue by JoMarieLe** [db-ui/design-feedback#129]
### The problem

Im Projekt ART.KOM ist gerade die Entscheidung fällig nach welchem Grid wir arbeiten (Web Desktop). Vielleicht kann das Thema ja priorisiert werden oder mehr Menschen stellen sich aktuell die Frage, ist ja eine benötigte Grundlage, um ein neues Projekt aufzubauen.

### The solution

Grid definieren

**Comment by leape** [comment]
Duplikat → https://github.com/db-ui/design-feedback/issues/82
