### ISSUE TITLE
Tag Critical - Weak ist widersprüchlich

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#13]
### Description

Critical und weak widersprechen sich etwas

### Suggestion/Example

Unterscheidung zwischen Semantic und Emphasis besser ausarbeiten.

**Comment by LSchroff** [comment]
Wird als Ticket in den Backlog aufgenommen und in einem der nächsten Sprints bearbeitet.

**Comment by leape** [comment]
Die Beschreibung von Weak/Strong wurde ergänzt.
---
Es besteht kein Widerspruch bzgl. Critical und Weak:
1. **Unterschiedliche Dringlichkeit**: „Weak“ signalisiert kritische Zustände, die weniger sofortige Aktion erfordern, während „Strong“ für dringende Probleme steht.
2. **Visuelle Hierarchie**: „Weak“ ermöglicht das Hervorheben von Problemen, ohne die Aufmerksamkeit zu sehr zu beanspruchen.
3. **Kontextabhängig**: „Weak“ verhindert Überalarmierung bei weniger dringenden oder wiederkehrenden Warnungen.
4. **Design-Harmonie**: Kritische Hinweise passen sich dezent in das Design ein, ohne dominant zu wirken.
5. **Barrierefreiheit**: Bietet flexible Kontrastoptionen für unterschiedliche visuelle Bedürfnisse.
