### ISSUE TITLE
Color Weak: Warning + Critical liegen sehr eng beieinander (fast nicht unterscheidbar)

### ISSUE THREAD

**Issue by MarianneMast** [db-ui/design-feedback#132]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [X] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [X] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Reproduction case

![Artboard](https://github.com/user-attachments/assets/85239ab2-335c-4501-a85d-bb8d3182cb5b)
![Bildschirmfoto 2024-10-10 um 08 32 11](https://github.com/user-attachments/assets/24457563-4455-4da6-be2d-a1fb6576e549)

### Expected

Die Farben Weak für Warning + Critical z.B. in den Tags, Notifications etc liegen im Farbkreis zu eng beieinander, sie sind fast nicht zu unterscheiden – siehe Screenshot

**Comment by LSchroff** [comment]
Wird durch anderes Issue abgedeckt: https://github.com/db-ui/design-feedback/issues/136
