### ISSUE TITLE
A11y: Placeholder contrast in form elements 

### ISSUE THREAD

**Issue by annsch** [db-ui/design-feedback#134]
### The problem

Aktuell haben Form Elemente wie input und select mit Placeholder keinen ausreichenden Kontrast. Das wird z.B. von Lighthouse (bzw. axe) angemeckert:

_"Background and foreground colors do not have a sufficient contrast ratio. Low-contrast text is difficult or impossible for many users to read."_

Hier auch nochmal der Link zu der Beschreibung, welches Kontrastverhätnis für Placeholder laut WCAG gelten muss:
https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/

<img width="369" alt="Screenshot 2024-10-10 at 16 03 20" src="https://github.com/user-attachments/assets/1797cfea-56dc-4250-954b-c45500ff3f8f">
<img width="534" alt="Screenshot 2024-10-10 at 16 08 55" src="https://github.com/user-attachments/assets/b3109921-edba-46b3-8bfb-f6e52fa781c5">

### The solution

Der Kontrast für Placeholder sollte erhöht werden, so dass er den WCAG Kriterien erfüllt und damit Testing Tools wie Lighthouse keinen Fehler mehr anzeigen. In Zukunft wird es wahrscheinlich immer mehr Projekte geben, in denen die A11y Richtlinien so streng sind, dass der Lighthouse Score in die Dev Pipeline mit aufgenommen wird. Das kann dazu führen, dass in den Projekten der Kontrast händisch angepasst wird, um die Testing Tools zufrieden zu stellen.

**Comment by annsch** [comment]
@mfranzke fyi

**Comment by leape** [comment]
@annsch @mfranzke habs für Stable hochpriorisiert
