### ISSUE TITLE
Figma: Icon für "Sort up" entspricht nicht der Vorschau (vertikal gespiegelt)

### ISSUE THREAD

**Issue by hannastephaniahahn** [db-ui/design-feedback#135]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [X] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

Core Icons v0.4.1

### Reproduction case

Wenn ich einem Icon-Button das Icon "Sort up" zuweise, wird dieses falsch herum dargestellt.

### Expected

Icon "Sort up" wird richtig herum dargestellt.

### Screenshots

![image](https://github.com/user-attachments/assets/bddf57bb-9625-4069-97f4-22999df68109)

**Comment by leape** [comment]
branch
fix: minor bugfixes

**Comment by oli-ver-h** [comment]
test comment

**Comment by oli-ver-h** [comment]
**Review**
✅ Done

**Findings**
🚀 None
