### ISSUE TITLE
Figma: Icon Button Ghost (functional, small): Rahmen für Focus ist falsch platziert

### ISSUE THREAD

**Issue by hannastephaniahahn** [db-ui/design-feedback#137]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v.0.4.1

### Reproduction case

Beim Icon Button Ghost (Functional, Small) ist der Rahmen für den Focus nicht richtig platziert

### Expected

Richtige Platzierung des Rahmens.

### Screenshots

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/9eb787cf-aebd-4fa3-bd09-f4e05f6805dc">

**Comment by leape** [comment]
branch
fix: minor bugfixes

**Comment by oli-ver-h** [comment]
Review
✅ Done

Findings
🚀 None
