### ISSUE TITLE
Input: Icon size sollte sm statt md sein

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#138]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v0.4.1

### Reproduction case

Leading + Last (chevron) icon sollte analog Select 
db-base-icon-font-size-sm
statt
db-base-icon-font-size-md
sein

### Expected

Korrigiere Größe des Leading + Chevron Icons auf db-base-icon-font-size-sm
### Screenshots

![image](https://github.com/user-attachments/assets/ecb3419d-d5e8-468d-a0cd-80f99a9d8f65)
![image](https://github.com/user-attachments/assets/fedbe5ef-37ca-4701-bdf5-d545861e51bc)

**Comment by leape** [comment]
Dev: https://github.com/db-ui/mono/issues/3367

**Comment by oli-ver-h** [comment]
Fix ist fertig. Gerne Reviewen:
https://www.figma.com/design/mlJ6R0GkfR15a93KSlqXtB/branch/JIhV9ipnhW8vsvOQgNtEdW/DB-UX-DS-v3---Core-Components-(Beta)---v0.5.0?m=auto&node-id=2-4058&t=xBf6vI18oQbZo4lJ-1
