### ISSUE TITLE
Tooltip Menü gewünscht

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#14]
### The problem

Der Inhaltsbereich des Tooltips lässt aktuell nur Text zu.

### The solution

Das Tooltip um eine weitere Variante erweitern, die auch andere Inhalte wie z.B. ein Menü zulässt.

### Examples

![image](https://github.com/db-ui/design/assets/6907841/82ce95f4-a262-4906-9f5f-6c174b8a11a8)

**Comment by LSchroff** [comment]
Duplikat: https://github.com/db-ui/design-feedback/issues/80
