### ISSUE TITLE
Checkbox functional hat keinen Haken mehr

### ISSUE THREAD

**Issue by JoMarieLe** [db-ui/design-feedback#141]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

0.4.1

### Reproduction case

Die Checkbox checked in size Medium und Small haben beide keinen Haken mehr, wenn man die Appearance auf Adaptive Size -> functional setzt

### Expected

Checkbox checked inkl. Haken in der Größe functional

### Screenshots

<img width="321" alt="image" src="https://github.com/user-attachments/assets/562f9b1b-a83b-4c9a-80f3-f68ba6d05374">

**Comment by leape** [comment]
Duplikat
Gibt leider vorerst keine Lösung, siehe https://github.com/db-ui/design-feedback/issues/111#issuecomment-2410898997
