### ISSUE TITLE
Tags (Desktop-Expressiv) sind nicht alle gleich hoch

### ISSUE THREAD

**Issue by YvonneYKuemmel** [db-ui/design-feedback#144]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v3

### Reproduction case

Removable Tags (Desktop-Expressiv) sind nicht so hoch wie die anderen Tags in dieser Größe 
<img width="790" alt="Bildschirmfoto 2024-10-16 um 13 58 07" src="https://github.com/user-attachments/assets/173d8825-959b-45b4-8a6c-6b27ee064c44">

### Expected

Removable Tags (Desktop-Expressiv) sind nicht so hoch wie die anderen Tags in dieser Größe

**Comment by oli-ver-h** [comment]
Fix ist fertig. Gerne Reviewen
https://www.figma.com/design/mlJ6R0GkfR15a93KSlqXtB/DB-UX-DS-v3---Core-Components-(Beta)---v0.5.0?m=auto&node-id=8-30478&t=BwqbUSa9USX9ztSQ-1
