### ISSUE TITLE
Infotexte analog zu Buttons in FullWidth- und AutoWidth-Ausprägungen

### ISSUE THREAD

**Issue by MaxMaulwurf** [db-ui/design-feedback#146]
### The problem

Bei der Komponente der Infotexte in der V3 (beta) gibt es noch keine Komponente, die in der Breite begrenzt ist und in der der Text umbricht. Aktuell kann dies durch Detach und manuelle Anpassung erreicht werden, ist dann aber keine Komponente aus dem Designsystem mehr.

### The solution

Komponenten unterteilen und eine Variante in FullWidth anbieten, die manuell in ihrer Breite angepasst werden kann.

**Comment by leape** [comment]
Duplicate: https://github.com/db-ui/design-feedback/issues/44
