### ISSUE TITLE
Fokusrahmen für dunkle Hintergrundfarben

### ISSUE THREAD

**Issue by LSchroff** [db-ui/design-feedback#155]
### The problem

Der blaue Fokusrahmen erreicht auf dunklen Hintergrundfarben nicht den benötigten Kontrastwert.

### The solution

Einen hellere Variante des Fokusrahmens für dunkle Hintergrundfarben.

**Comment by mfranzke** [comment]
Für die dunkle Hintergrundfarbe haben wir doch bereits einen helleren blauton:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/cda5ecfe-4a7a-4106-9e65-43545ceea687">

**Comment by leape** [comment]
Um das zu beurteilen fehlen zusätziche Infos.
Wie @mfranzke geschrieben hat: der Fokus-Rahmen der V3 ist für die definierten Hintergründe im System eigentlich accessible für Light und Dark Mode.
