### ISSUE TITLE
Navigation Desktop Level 2+ Popover verschoben

### ISSUE THREAD

**Issue by JoMarieLe** [db-ui/design-feedback#161]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v.0.5.0

### Reproduction case

Beim Navigation Desktop in Level 2+ ist das weiße Popover verschoben.
<img width="453" alt="image" src="https://github.com/user-attachments/assets/55aa4514-beb0-4fc2-8399-a393fb060d38">

### Expected

Popover ist nicht verschoben

**Comment by leape** [comment]
@JoMarieLe - besteht der Fehler noch, ich kann ihn in der aktuellsten Version nicht nachvollziehen:
![Image](https://github.com/user-attachments/assets/b890e453-cdb3-4652-a7e8-20f607bdf8e6)

**Comment by JoMarieLe** [comment]
Passt, hab das Problem bei mir auch nicht mehr. Auch wenn die alten Elemente jetzt vollends kaputt sind funktionieren die neuen :D

**Comment by leape** [comment]
@JoMarieLe Mit der Einführung der Stack-Komponente wird die Navigation eh auch nochmal überarbeitet werden müssen.
Dann schließ ich das Issue mal.
Danke für die schnelle Rückmeldung.
