### ISSUE TITLE
Progress Button

### ISSUE THREAD

**Issue by Anna-Welzenbach** [db-ui/design-feedback#170]
### The problem

When users double-click the call to action, feedback is missing and might lead to confusion about the status of the process/progress.

### The solution

A progress button will help to avoid this mess. It prevents duplicate orders by disabling the button after the first click. It displays a progress bar over the button to let users know their order is processing. Users get clear and immediate feedback, so they won’t feel the need to click the button again.

### Examples

![progress_button-2seconds](https://github.com/user-attachments/assets/03acdb9f-3aba-4da1-9bf6-a2fdde1103b6)

**Comment by leape** [comment]
Dupllikat => ttps://github.com/db-ui/design-feedback/issues/78
