### ISSUE TITLE
Delete hover animation of Popover component

### ISSUE THREAD

**Issue by vladi94** [db-ui/design-feedback#171]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v0.5.3

### Reproduction case

Use a Popover component
Active content slot
Put in the content you like
(pop as overlay or whatever)
Use Prototyping mode
Hover over the Popover

### Expected

No hover animation on the Popover - i don't see a reason why its there. It just darkens the content and the inputs/buttons within the content do have a hover functionality anyways. 
It is a little bit annoying to remove the hover functionality manually.

### Screenshots

No Hover/Mouse-Over on the Popover - everythings fine:
<img width="2244" alt="image" src="https://github.com/user-attachments/assets/4dbd19a6-c7f7-4049-9cbd-79bb0d410d65">

Hover/Mouse-Over on the Popover - complete content gets darker aswell:
<img width="2244" alt="image" src="https://github.com/user-attachments/assets/ba5c8324-82e8-4404-b8d5-81cf8781d475">

**Comment by leape** [comment]
Thanks for this issue @vladi94. It seems that the non-interactive card variant has prototyping assigned. We will fix this in the next release.

**Comment by vladi94** [comment]
@leape thanks!
