### ISSUE TITLE
Erklär-Videos im MaPo werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by LSchroff** [db-ui/design-feedback#182]
### Link

https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/db-ux-design-system/version-3/principles/adaptive

### Description

Die eingebetteten Videos im MaPo können nicht mehr angeschaut werden, wahrscheinlich ist der Link kaputt.

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/23148455-c5e6-4a27-b1df-ff78164d9501">

### Suggestion/Example

Korrekte Links wieder einpflegen.

**Comment by mfranzke** [comment]
@LSchroff bei mir werden sie angezeigt. Sowohl im Netz, als auch außerhalb.

**Comment by leape** [comment]
Kann es auch nicht reproduzieren.
