### ISSUE TITLE
Input Default - Leading Icon - Functional - wird abgeschntten

### ISSUE THREAD

**Issue by vschramm** [db-ui/design-feedback#183]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Reproduction case

Input Beta alle Label Varianten. Functional. Wenn ich die Variante mit Icon Vorne auswähle (oder auch vorne und hinten) wird das Icon vorne abgeschnitten. Wenn ich Reset All mache, um eventuelle Verschiebugen zu fixen, wird leider auch Functional auf Regular zurückgesetzt.

### Expected

Ich erwarte dass die Icons im Input Feld in allen Densities richtig dargestellt wird.

### Screenshots

<img width="360" alt="image" src="https://github.com/user-attachments/assets/773af8fb-d25a-4ec4-8898-18f375831fd2">

**Comment by leape** [comment]
Duplikat: https://github.com/db-ui/design-feedback/issues/175
Wird mit dem nächsten Release gefixt.
