### ISSUE TITLE
Navigation Item level 2 / Popover ist verzogen

### ISSUE THREAD

**Issue by JoMarieLe** [db-ui/design-feedback#187]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

v.0.6.1

### Reproduction case

Wenn ich das horizontale Navigation item auf Level 2 stelle dann verschiebt sich der content unter das Element

### Expected

Der Content sitzt richtig im Popover Element :D

### Screenshots

<img width="407" alt="image" src="https://github.com/user-attachments/assets/a5e74559-3001-4869-9d0f-903eac3cee19">

**Comment by leape** [comment]
Kann nicht reproduziert werden.
