### ISSUE TITLE
Warning Farbe funktioniert nicht

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#37]
### Which design system content is impacted?

- [X] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Die Farbe für warning funktioniert für mich leider überhaupt nicht. Im dunklen Bereich ist die Farbe auch nicht mehr sichtbar. Anstatt Braun vielleicht eher ein Orange?
-
Die Farbe sieht nicht nach Warnung aus.

### Expected

Die Warning-Farbpalette sollte eher Orange aussehen.

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/f2fd064c-6dc7-4191-8fb9-40937cc26973)

**Comment by LSchroff** [comment]
Wird durch anderes Issue abgedeckt: https://github.com/db-ui/design-feedback/issues/136
