### ISSUE TITLE
Mehrzeilige Helpermessage wird ausgepunktet

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#44]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Mehrzeilige Helpermessage wird ausgepunktet

### Expected

Die Helper Message sollte umbrechen

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/339615a2-d9da-4d1a-8c76-af8b50e6bf93)

**Comment by leape** [comment]
Wird über Full Width gelöst.

**Comment by leape** [comment]
branch
fix: minor bugfixes

**Comment by oli-ver-h** [comment]
Review
✅ Done

Findings
🚀 None
