### ISSUE TITLE
Doku: Farben

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#64]
### Link

https://marketingportal.extranet.deutschebahn.com/marketingportal/Design-Anwendungen/db-ux-design-system/version-3/foundation/colors

### Description

korrekte Anwendung von Farben in Layout/Screens mit Beispielen besser darstellen

### Suggestion/Example

s.o.

**Comment by LSchroff** [comment]
Wird als Ticket mit aufgenommen und in einem der kommenden Sprints bearbeitet.
