### ISSUE TITLE
Mehrzeilige Checkbox und Radio Labels

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#67]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Die Labels von Checkbox und Radio können nur über einen manuellen Umbruch mehrzeilig werden.

### Expected

Prüfen, ob die Komponenten neben Auto Width auch ein Full Width verhalten aufweisen sollte.

**Comment by leape** [comment]
Wird über Full Width gelöst.

**Comment by leape** [comment]
branch
fix: minor bugfixes

**Comment by oli-ver-h** [comment]
Review
✅ Done

Findings
- Checkbox Indeterminate Full (medium/small): Alignment center left 
- Checkbox Checked Full (medium/small): Alignment center left

Fixes
- Checkbox Indeterminate Full (medium/small): Alignment top left
- Checkbox Checked Full (medium/small): Alignment center left
