### ISSUE TITLE
Button Bug

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#7]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [X] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

Beta-1

### Reproduction case

Umstellen eines „AutoWidth“ Buttons (probiert bei medium, outlined) auf „FullWidth“ macht den ganzen Button kaputt. Der Schwarze Rahmen wird zu schmal und das graue wird super breit, händisches skalieren ist zwar möglich, aber der graue Hintergrund bleibt breiter als der schwarze Rahmen.

### Expected

Das Umstellen von Auto Width auf Full Width soll keine visuellen Fehler bringen

**Comment by LSchroff** [comment]
Wird als Ticket mit aufgenommen und in einem der kommenden Sprints bearbeitet.

**Comment by leape** [comment]
Bug kann in der neuesten Sketch Version nicht reproduziert werden.
