### ISSUE TITLE
Verwendung / Aufbau Accordion unklar

### ISSUE THREAD

**Issue by leape** [db-ui/design-feedback#8]
### Description

Eine einfache Möglichkeit mehr als 3 Accordion Elemente zu verwenden wäre super. Das Symbol lässt sich leider nicht einfach mehrfach untereinander legen, da dann die letzte Linie fehlt und man die auch nicht in der Komponente nachträglich einfügen kann durch z.B. Layer Styles oder overrides.

### Suggestion/Example

Der Umgang mit den Sketch-Komponenten, die ✂️ detached werden können muss in der Dokumentation besser erklärt werden.

**Comment by LSchroff** [comment]
Die Dokumentation (Onboarding Files) wird kommenden Sprint bearbeitet.

**Comment by leape** [comment]
[Onboarding Sketch - Detaching Components](https://www.figma.com/board/DU6mi4bAsJW82uJ8jLbyin/DB-UX-DS-3---Onboarding-Sketch?node-id=2288-395&node-type=section&t=OAclWf1tSnyC73g2-11
)
