### ISSUE TITLE
Input (Active) ohne Validierung ein Trailing-Icon hinzufügen

### ISSUE THREAD

**Issue by MaxMaulwurf** [db-ui/design-feedback#92]
### The problem

Aktuell ist der Input (Active) ohne Validierung ohne Trailing-Icon vorhanden. Dadurch lassen sich Inputfelder wie bspw. eine Datums- oder Zeitauswahl nicht abbilden. 
![image](https://github.com/user-attachments/assets/32324de6-aa12-4af5-ad93-80f745f835ef)

### The solution

Inputfeldern (Active) mit Trailing-Icon ausstatten.
![image](https://github.com/user-attachments/assets/c058707a-5a5a-4923-8eab-21234dc2442a)

**Comment by sissihamel** [comment]
branch: fix input missing variants (abstract / child branch in minor fixes)
